Gemfile
Gemfile.lock
app/models/date_option.rb
app/models/participation.rb
app/models/reunion.rb
app/models/suggested_destination.rb
app/models/user.rb
db/migrate/20221129114233_add_origin_to_users.rb
db/migrate/20221129115213_create_reunions.rb
db/migrate/20221129115356_add_description_to_reunions.rb
db/migrate/20221129140757_create_participations.rb
db/migrate/20221129141611_create_date_options.rb
db/migrate/20221129143249_acts_as_votable_migration.rb
db/migrate/20221129145823_create_suggested_destinations.rb
db/schema.rb
test/models/date_option_test.rb
test/models/participation_test.rb
test/models/reunion_test.rb
test/models/suggested_destination_test.rb

we've added all the models that reunion will need.
please if you need to amend them, run a migration

Lots of models

---

Gemfile.lock
app/controllers/reunions_controller.rb
app/views/reunions/index.html.erb
app/views/reunions/new.html.erb
config/routes.rb
test/controllers/reunions_controller_test.rb

Created reunion controller, routes and new view

Creating reunion controller

---

app/controllers/participation_controller.rb
app/models/participation.rb
test/controllers/participation_controller_test.rb

added participations controller

Participationcontroller

---

app/controllers/participations_controller.rb
config/routes.rb

added a nested route for participations
changed the participations controller name to plural

nested routes

---

app/assets/stylesheets/components/_addparticipant.scss
app/controllers/participations_controller.rb
app/models/participation.rb
app/views/participations/new.html.erb

Created method for participations controller

Addedbuttonstoview

---

app/assets/stylesheets/components/_footer.scss

I changed the footer to sticky to the page bottom

Fixed footer to sticky to the page bottom

---

app/assets/stylesheets/components/_footer.scss

removing changes

---

app/views/reunions/show.html.erb

changed the date options in show page reunion when we add a date to calendar

displayed date options in reunion show page

---

app/assets/stylesheets/config/_fonts.scss

- Change the font style (poppins - light)

fontpoppinlight

---

app/assets/stylesheets/components/_btn.scss
app/views/pages/home.html.erb

- corrections in button's style of homepage

button-create

---

app/assets/stylesheets/components/_destination-info.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_reunion-sum-banner.scss
app/assets/stylesheets/components/_title-destination.scss
app/views/suggested_destinations/show.html.erb

- working on reunion summary page 
- since the API of Amadeus does not working and we are trying to find another strategy, I started with the frond end and then I will come back to the back end
- Style of the banner of reunion summary page
- Style of destination cards

bannerreunionsummary

---

app/assets/stylesheets/components/_btn.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_reunion-home.scss
app/assets/stylesheets/components/_reunion_show_banner.scss
app/assets/stylesheets/components/_wrapper.scss
app/controllers/participations_controller.rb
app/models/reunion.rb
app/views/participations/new.html.erb
app/views/reunions/show.html.erb
db/seeds.rb

Added the participants to the show page and styled the show page.  Edit seeds file to be organised alphabetically

Newparticipantscss

---

app/assets/stylesheets/components/_gallery.scss

- update the gallery of homepage

galleryphotos

---

app/assets/stylesheets/components/_cards.scss

homepagecardsorder

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_gallery.scss

added button "notify my friends" logic
+ added names on seed

notify button logic

---

app/views/reunions/show.html.erb
db/seeds.rb

button logic "notify my friends"
name on seeds

adding button logic and name to seeds

---

app/assets/stylesheets/components/_alert-date-option.scss
app/assets/stylesheets/components/_index.scss
app/controllers/date_options_controller.rb
app/models/reunion.rb
app/views/date_options/index.html.erb
app/views/reunions/show.html.erb
config/routes.rb

added voting logic and alert after button

Vote date option

---

app/assets/stylesheets/components/_btn.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_gallery.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_reunion_show_banner.scss
app/assets/stylesheets/components/_wrapper.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Polished the home css and created functions for the navbar

Index style and navbar functions actived

---

db/migrate/20221205142503_add_has_voted_dates_to_participations.rb
db/schema.rb

re added boolean to schema

---

app/assets/stylesheets/components/_cards.scss
app/controllers/date_options_controller.rb
app/views/date_options/index.html.erb
config/routes.rb

Votable gem is now working
Show table for vote counting is styled

Votablecheckbox

---

app/assets/stylesheets/components/_btn.scss
app/assets/stylesheets/components/_cards.scss
app/views/date_options/new.html.erb
app/views/pages/home.html.erb
app/views/participations/new.html.erb
app/views/reunions/new.html.erb
app/views/reunions/show.html.erb
db/schema.rb

Patronised all of the primary buttons

Padronized buttons

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_wrapper.scss
app/javascript/controllers/index.js
app/javascript/controllers/tom_select_controller.js
app/views/participations/new.html.erb
package-lock.json
package.json
yarn.lock

changed the user input page with a tom select selector

changed user selection

---

app/assets/stylesheets/components/_gallery.scss

- change little style details in gallery

galleryarrow

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_reunion-home.scss

- cards (center - padronize)
- margin on top and bottom (padronize)

homepagestructure

---

Gemfile
Gemfile.lock
app/controllers/date_options_controller.rb
app/helpers/application_helper.rb
app/service_objects/trip_search.rb
config/initializers/geocoder.rb

adds dynamic date options based on most upvoted date option

Dateinterpolate

---

app/javascript/controllers/display_destination_controller.js
app/javascript/controllers/index.js
app/service_objects/trip_search.rb
app/views/suggested_destinations/new.html.erb
db/schema.rb
yarn.lock

show different destinations click on suggest more destination

shows another destination

---

app/views/suggested_destinations/new.html.erb

fixed rolling destination we can now see several suggested destination

fixed rolling destination

---

app/views/reunions/new.html.erb

button on create reunion spaced evenly

buttons spaced evenly

---

app/controllers/date_options_controller.rb
app/javascript/controllers/participations_controller.js
app/views/participations/_reunion_participants_block.html.erb

- participation controller javascript
- pop to add participants
- reunion_participations_block

participantspopup

---

app/views/date_options/index.html.erb

removed the table text repeated in each row

removed votes from each table row

---

config/initializers/default_meta.rb
config/meta.yml

added meta tags

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_create-form-style.scss
app/views/reunions/new.html.erb
app/views/reunions/show.html.erb

create a new reunion page styled

---

app/assets/stylesheets/components/_card-trip.scss
app/assets/stylesheets/components/_participants.scss
app/assets/stylesheets/components/_suggested-destination-card.scss
app/views/suggested_destinations/_side_panel.html.erb
app/views/suggested_destinations/new.html.erb

added style to destination page

suggested destination page style

---

app/views/date_options/index.html.erb

fixed an error that showed on the last merge

Fixederror
